### ISSUE TITLE
interactive_objectDetection crashed at high alphas

### ISSUE THREAD

**Issue by devSJR** [Brauckhoff/biopixR#1]
In the interactive GUI (interactive_objectDetection), the interface breaks down if you choose the alpha too large.
You could catch the error via the _try_ function?

**Comment by Brauckhoff** [comment]
Yes, you are absolutely right. I implemented the changes in commit 75c09fd. It should no longer be a problem. The sliders will now automatically reset to their previous values if any adjustments would otherwise cause an error.

**Comment by devSJR** [comment]
Great, this commit fixes the issue.

**Comment by devSJR** [comment]
I close my issue.

**Comment by devSJR** [comment]
Great, this commit fixes the issue.
