### ISSUE TITLE
Devtools error

### ISSUE THREAD

**Issue by Sshivji** [Brauckhoff/biopixR#2]
Hello, 
I am using R version 4.3.2 on windows 11 and while installing a package devtools I encountered the following issue:
> devtools::install_github("Brauckhoff/biopixR", ref="0.2.2")
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called ‘miniUI’.
  So I am not sure what does that means? 
  Can you help me figure it out?

**Comment by Brauckhoff** [comment]
Currently, I haven't identified a compelling reason for the apparent necessity of the "miniUI" package. It's worth noting that "miniUI" is typically employed for Shiny apps, a feature that hasn't been utilized in this package. To address the issue, please attempt to install the package using the command: install.packages("miniUI"). I plan to delve deeper into this matter in the future, particularly while implementing Continuous Integration for Windows, to better understand and resolve the underlying problem.

**Comment by Brauckhoff** [comment]
We focused on establishing a continuous integration (CI) workflow designed for conducting R-CMD-checks on Windows. However during this process, we did not encounter any issues related to the installation procedures.
