### ISSUE TITLE
Limit number of CPU cores?

### ISSUE THREAD

**Issue by devSJR** [Brauckhoff/biopixR#3]
The latest version of biopixR appears to use all CPU cores for parallel processing. Here is my output:
Loading required package: magick
Linking to ImageMagick 6.9.11.60
Enabled features: fontconfig, freetype, fftw, heic, lcms, pango, webp, x11
Disabled features: cairo, ghostscript, raw, rsvg
Using 20 threads
Loading required package: tcltk
Loading required package: foreach

While this is good, it for fast processing it might be an issue on older machines with fewer cores. I migth be worth to consider that the user can either define the number of cores during the start, in a config … or to set that maximum 80-90 % of the cores are used.

**Comment by Brauckhoff** [comment]
While this is an unusual observation, it shouldn't be a cause for concern. I have limited the number of cores in use to 75% in the functions that use parallel processing to ensure a controlled use of resources.
